package io.github.wilfredluijk.navalsdk

import com.fasterxml.jackson.databind.JsonNode
import io.github.wilfredluijk.navalsdk.internal.*
import io.github.wilfredluijk.navalsdk.tactical.*
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test

/** Expected outputs were executed in the original Python SDK, never generated by Kotlin. */
class PythonParityTest {
    private val cases =
        Wire.parse(
                checkNotNull(javaClass.getResourceAsStream("/python-parity.json"))
                    .bufferedReader()
                    .use { it.readText() }
            )["cases"]
            .toList()
    private val specs = welcomeFixture().shipSpecs

    private fun same(expected: JsonNode, actual: JsonNode, context: String) {
        when {
            expected.isNumber -> {
                assertTrue(actual.isNumber, context)
                assertEquals(expected.asDouble(), actual.asDouble(), 1e-8, context)
            }
            expected.isArray -> {
                assertEquals(expected.size(), actual.size(), context)
                expected.indices().forEach { same(expected[it], actual[it], "$context[$it]") }
            }
            expected.isObject -> {
                assertEquals(expected.size(), actual.size(), context)
                expected.properties().forEach { (k, v) ->
                    assertTrue(actual.has(k), "$context.$k")
                    same(v, actual[k], "$context.$k")
                }
            }
            else -> assertEquals(expected, actual, context)
        }
    }

    private fun JsonNode.indices() = 0 until size()

    private fun node(value: Any?): JsonNode = Wire.mapper.valueToTree(value)

    private fun track(d: JsonNode) =
        Track(
            d.int("track_id"),
            d.str("kind"),
            Vec2.fromJson(d["pos"]),
            Vec2.fromJson(d["observed_pos"]),
            Vec2.fromJson(d["vel"]),
            d.int("last_seen_tick"),
            d.int("first_seen_tick"),
            d.int("last_active_tick"),
            d.num("confidence"),
            d.str("source"),
        )

    @Test
    fun `50 Python compass distance and intercept vectors`() {
        cases
            .filter { it.str("kind") == "math" }
            .forEachIndexed { i, c ->
                val a = Vec2.fromJson(c["a"])
                val b = Vec2.fromJson(c["b"])
                val actual =
                    Wire.obj().put("distance", distance(a, b)).put("bearing", bearingTo(a, b))
                actual.set<JsonNode>(
                    "lead",
                    leadTarget(a, b, Vec2.fromJson(c["v"]), c.num("speed"))?.toJson()
                        ?: Wire.mapper.nullNode(),
                )
                same(c["expected"], actual, "math $i")
            }
    }

    @Test
    fun `25 Python aiming command vectors`() {
        cases
            .filter { it.str("kind") == "command" }
            .forEachIndexed { i, c ->
                same(
                    c["expected"],
                    Command(.6, -.2)
                        .fireAt(
                            Vec2.fromJson(c["target"]),
                            Vec2.fromJson(c["origin"]),
                            Vec2.fromJson(c["vel"]),
                        )
                        .toJson(c.int("tick"), "parity"),
                    "command $i",
                )
            }
    }

    @Test
    fun `35 Python helm vectors including walls and overdrive`() {
        cases
            .filter { it.str("kind") == "helm" }
            .forEachIndexed { i, c ->
                val steering =
                    Helm(specs).steerToBearing(WorldView.fromJson(c["view"]).me, c.num("target"))
                same(c["expected"], node(listOf(steering.throttle, steering.rudder)), "helm $i")
            }
    }

    @Test
    fun `60 sequential Python active passive and dead reckoned tracking states`() {
        val tracker = Tracker(specs)
        cases
            .filter { it.str("kind") == "tracker" }
            .forEachIndexed { i, c ->
                val tracks = tracker.update(WorldView.fromJson(c["view"]))
                assertEquals(c["expected"].size(), tracks.size)
                tracks.forEachIndexed { j, t ->
                    val e = track(c["expected"][j])
                    assertEquals(e.trackId, t.trackId)
                    assertEquals(e.source, t.source)
                    assertEquals(e.lastSeenTick, t.lastSeenTick)
                    assertEquals(e.lastActiveTick, t.lastActiveTick)
                    assertEquals(e.firstSeenTick, t.firstSeenTick)
                    same(e.pos.toJson(), t.pos.toJson(), "track pos $i")
                    same(e.vel.toJson(), t.vel.toJson(), "track velocity $i")
                    same(e.observedPos.toJson(), t.observedPos.toJson(), "track anchor $i")
                }
            }
    }

    @Test
    fun `40 Python gunner solutions with powerups and self splash guard`() {
        cases
            .filter { it.str("kind") == "gunner" }
            .forEachIndexed { i, c ->
                val v = WorldView.fromJson(c["view"])
                val solution = Gunner(specs).solve(v.me, track(c["track"]), v, "long_range_salvo")
                val actual =
                    solution?.let {
                        Wire.obj()
                            .put("bearing_deg", it.bearingDeg)
                            .put("range", it.range)
                            .put("target_id", it.targetId)
                            .apply { set<JsonNode>("aim_pos", it.aimPos.toJson()) }
                    } ?: Wire.mapper.nullNode()
                same(c["expected"], actual, "gunner $i")
            }
    }

    @Test
    fun `30 sequential Python evasion transitions`() {
        val evader = Evader(evasionTicks = 3, cooldownTicks = 3)
        cases
            .filter { it.str("kind") == "evader" }
            .forEachIndexed { i, c ->
                val v = WorldView.fromJson(c["view"])
                same(
                    c["expected"],
                    evader.update(v)?.toJson(v.tick, v.matchId) ?: Wire.mapper.nullNode(),
                    "evader $i",
                )
                assertEquals(c.str("state"), evader.state.name.lowercase())
            }
    }
}
